spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://db-notification-service:5432/notificationdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group

security:
  jwt:
    secret: ${JWT_SECRET:default-secret}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
